name: someapp
description: Sample Flutter project for firebase.

publish_to: "none"

version: 1.0.0

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  flutter_riverpod: ^0.14.0+3 
  cloud_functions: ^3.2.4
  cloud_firestore: ^ 3.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test: 
    sdk: flutter
  http: ^0.13.3

flutter:
  uses-material-design: true
