name: someapp
description: Sample Flutter project for firebase.

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  flutter_riverpod: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
