name: someapp
description: Sample Flutter project for firebase.

publish_to: "none"

version: 1.0.0

environment:
  sdk: '>=2.12.0-133.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1 
  flutter_riverpod: ^0.12.1
  cloud_firestore: ^0.14.4 
  cloud_functions: ^0.7.2 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
