// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHPMf_l3tessosiXsZ3oQPkDtuB9u80Ds',
    appId: '1:845242923813:web:d7449cf58439b15b2e78cc',
    messagingSenderId: '845242923813',
    projectId: 'testproject2-1ed80',
    authDomain: 'testproject2-1ed80.firebaseapp.com',
    databaseURL: 'https://testproject2-1ed80.firebaseio.com',
    storageBucket: 'testproject2-1ed80.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLzUszbLbNMX_GVkm_agx2pBfghggxgYs',
    appId: '1:845242923813:android:a69304fcc3bb3fcb2e78cc',
    messagingSenderId: '845242923813',
    projectId: 'testproject2-1ed80',
    databaseURL: 'https://testproject2-1ed80.firebaseio.com',
    storageBucket: 'testproject2-1ed80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ7WRWT2B8jx22j5CmBbcLvUk47Ir6OHY',
    appId: '1:845242923813:ios:b72b713169fb2af92e78cc',
    messagingSenderId: '845242923813',
    projectId: 'testproject2-1ed80',
    databaseURL: 'https://testproject2-1ed80.firebaseio.com',
    storageBucket: 'testproject2-1ed80.appspot.com',
    iosClientId: '845242923813-7f1m0n476s1lj0bs5dct71rgd5v45i1m.apps.googleusercontent.com',
    iosBundleId: 'sid.flutterfire.someapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ7WRWT2B8jx22j5CmBbcLvUk47Ir6OHY',
    appId: '1:845242923813:ios:b72b713169fb2af92e78cc',
    messagingSenderId: '845242923813',
    projectId: 'testproject2-1ed80',
    databaseURL: 'https://testproject2-1ed80.firebaseio.com',
    storageBucket: 'testproject2-1ed80.appspot.com',
    iosClientId: '845242923813-7f1m0n476s1lj0bs5dct71rgd5v45i1m.apps.googleusercontent.com',
    iosBundleId: 'sid.flutterfire.someapp',
  );
}
